# -*- coding: utf-8 -*-
"""MoE-Omics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nhcGXzR9E4ZH9Lo4-X3ibhHcmeNbv19
"""

# Install library bioinformatika standar
!pip install scanpy scvi-tools anndata torch

import scanpy as sc
import scvi
import torch
import numpy as np
import gc  # Garbage collector untuk membersihkan RAM
from sklearn.model_selection import train_test_split

# Install missing libraries
!pip install -q scanpy scvi-tools

# ==========================================
# 3. LOAD DATA RIIL (CITE-seq Asli)
# ==========================================
print("Sedang memuat dataset CITE-seq asli...")
adata = scvi.data.pbmc_seurat_v4_cite_seq()

# ====================================================
#  POTONG DATA
# ====================================================
print("Memotong dataset ke 15.000 sel secara acak (Subsampling)...")
sc.pp.subsample(adata, n_obs=15000, random_state=42)

# Hapus variabel yang tidak terpakai dari memori
gc.collect()

# Pastikan nama sel unik
adata.obs_names_make_unique()

print("Sedang memproses RNA (Normalisasi & Seleksi 2000 fitur)...")
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, n_top_genes=2000, subset=True)

# Ambil data RNA (sebagai input)
rna_raw = adata.X.toarray() if hasattr(adata.X, 'toarray') else adata.X

# ====================================================
# DETEKSI LOKASI PROTEIN
# ====================================================
obsm_keys = list(adata.obsm.keys())
if 'protein_counts' in adata.obsm:
    prot_obj = adata.obsm['protein_counts']
elif 'protein_expression' in adata.obsm:
    prot_obj = adata.obsm['protein_expression']
elif 'protein' in adata.obsm:
    prot_obj = adata.obsm['protein']
else:
    prot_keys =[k for k in obsm_keys if 'protein' in k.lower()]
    if not prot_keys:
        raise ValueError(f"Data protein tidak ditemukan! Keys: {obsm_keys}")
    prot_obj = adata.obsm[prot_keys[0]]

# Ambil matriks datanya dengan aman
prot_raw = prot_obj.to_numpy() if hasattr(prot_obj, 'to_numpy') else np.array(prot_obj)

print(f"\n✅ Data Berhasil Dimuat dan Dipotong!")
print(f"Jumlah Sel Sekarang: {rna_raw.shape[0]}")
print(f"Jumlah Gen (RNA): {rna_raw.shape[1]}")
print(f"Jumlah Protein: {prot_raw.shape[1]}")

print("\nMemisahkan Data Latih & Uji...")
rna_train, rna_test, prot_train, prot_test = train_test_split(
    rna_raw, prot_raw, test_size=0.2, random_state=42
)

# Bersihkan sisa RAM sebelum masuk Tensor
del rna_raw, prot_raw, adata
gc.collect()

# Konversi ke Tensor PyTorch
rna_train_t = torch.FloatTensor(rna_train)
prot_train_t = torch.FloatTensor(prot_train)
rna_test_t = torch.FloatTensor(rna_test)
prot_test_t = torch.FloatTensor(prot_test)

print(f"📊 Shape Data Latih:")
print(f"   RNA Train Tensor: {rna_train_t.shape}")
print(f"   Protein Train Tensor: {prot_train_t.shape}")

from torch.utils.data import DataLoader, TensorDataset
import torch.optim as optim

def train_cmat_moe(rna_data, protein_data, epochs=50, batch_size=64, learning_rate=1e-3):
    # Pindahkan model ke GPU jika tersedia
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Menggunakan perangkat: {device}")

    # Inisialisasi Model
    # Sesuaikan dim_rna dan dim_prot dengan shape data asli
    model = CMAT_MoE(dim_rna=rna_data.shape[1], dim_prot=protein_data.shape[1], embed_dim=128).to(device)

    # Data Loader
    dataset = TensorDataset(rna_data, protein_data)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    # Optimizer & Loss (Menggunakan MSE untuk regresi protein)
    optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-5)
    criterion = nn.MSELoss()

    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for batch_rna, batch_prot in loader:
            batch_rna, batch_prot = batch_rna.to(device), batch_prot.to(device)

            # Forward Pass
            optimizer.zero_grad()
            predictions = model(batch_rna, batch_prot)

            # Loss Calculation (Target bisa disesuaikan, misal memprediksi protein dari RNA)
            loss = criterion(predictions, batch_prot)

            # Backward Pass
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        if (epoch + 1) % 10 == 0:
            print(f"Epoch [{epoch+1}/{epochs}], Loss: {total_loss/len(loader):.4f}")

    return model

# Jalankan pelatihan dengan data riil yang sudah dimuat sebelumnya
# trained_model = train_cmat_moe(rna_data, protein_data)

import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt

# ==========================================
# 4. ARSITEKTUR MODEL
# ==========================================
print("Mempersiapkan Model Deep Learning...")

# Membuat DataLoader (Memecah 12.000 data latih menjadi kelompok kecil / batch)
# Batch size 256 sangat aman untuk RAM
train_dataset = TensorDataset(rna_train_t, prot_train_t)
train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)

test_dataset = TensorDataset(rna_test_t, prot_test_t)
test_loader = DataLoader(test_dataset, batch_size=256, shuffle=False)

# Mendefinisikan Jaringan Saraf Tiruan (Multi-Layer Perceptron)
class CITESeqPredictor(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(CITESeqPredictor, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 512),    # Layer 1 (Input ke Hidden 1)
            nn.BatchNorm1d(512),          # Menstabilkan pelatihan
            nn.ReLU(),                    # Fungsi aktivasi
            nn.Dropout(0.3),              # Mencegah model menghafal (Overfitting)

            nn.Linear(512, 256),          # Layer 2 (Hidden 1 ke Hidden 2)
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(256, output_dim)    # Layer 3 (Output / Prediksi Protein)
        )

    def forward(self, x):
        return self.network(x)

# Ambil dimensi otomatis dari data
input_size = rna_train_t.shape[1]   # 2000 Gen RNA
output_size = prot_train_t.shape[1] # Jumlah Protein (Misal: 227)

model = CITESeqPredictor(input_dim=input_size, output_dim=output_size)

# Deteksi GPU agar pelatihan 10x lebih cepat (Jika diaktifkan di Colab)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"Model siap! Menggunakan perangkat: {device}")

# Pengaturan Algoritma Pembelajaran
criterion = nn.MSELoss() # Menghitung error dengan Mean Squared Error
optimizer = optim.Adam(model.parameters(), lr=0.001) # Optimizer standar terbaik

# ==========================================
# 5. TRAINING LOOP
# ==========================================
epochs = 20 # Model akan belajar dengan mengulang data 20 kali
history_loss =[]

print(f"\n🚀 Memulai Pelatihan selama {epochs} Epochs...\n")

for epoch in range(epochs):
    model.train() # Setel model ke mode belajar
    total_loss = 0.0

    for batch_rna, batch_prot in train_loader:
        # Pindahkan data ke GPU/CPU
        batch_rna, batch_prot = batch_rna.to(device), batch_prot.to(device)

        # 1. Prediksi protein dari RNA
        predictions = model(batch_rna)

        # 2. Hitung seberapa salah prediksinya (Loss)
        loss = criterion(predictions, batch_prot)

        # 3. Perbarui otak model (Backpropagation)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    # Catat rata-rata error di epoch ini
    avg_loss = total_loss / len(train_loader)
    history_loss.append(avg_loss)

    # Print perkembangan setiap 2 epoch
    if (epoch + 1) % 2 == 0 or epoch == 0:
        print(f"Epoch [{epoch+1}/{epochs}] 📉 Training Loss (Error): {avg_loss:.4f}")

print("\n✅ Pelatihan Selesai!")

# ==========================================
# 6. VISUALISASI HASIL BELAJAR
# ==========================================
plt.figure(figsize=(8, 5))
plt.plot(range(1, epochs+1), history_loss, marker='o', color='b', label='Training Loss')
plt.title("Model Error Decrease Curve (Training Loss)")
plt.xlabel("Epoch")
plt.ylabel("Mean Squared Error (MSE)")
plt.grid(True)
plt.legend()
plt.show()

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# 7. EVALUASI PADA DATA UJI (TEST DATA)
# ==========================================
print("Menguji model pada Data Uji yang belum pernah dilihat...")

# 1. Posisikan model dalam mode Evaluasi (mematikan Dropout & BatchNorm)
model.eval()

# 2. Lakukan Prediksi Tanpa Menghitung Gradien (Hemat Memori & Lebih Cepat)
with torch.no_grad():
    # Pindahkan data uji ke GPU/CPU sesuai perangkat yang aktif
    rna_test_device = rna_test_t.to(device)

    # Dapatkan tebakan (prediksi) model
    prot_pred_t = model(rna_test_device)

    # Kembalikan ke CPU dan ubah ke Numpy Array agar bisa digambar
    y_pred = prot_pred_t.cpu().numpy()
    y_true = prot_test_t.cpu().numpy()

# Karena datanya sangat besar (3.000+ sel x 227 protein = ~680.000 titik),
# kita ambil sampel acak 20.000 titik agar visualisasi tidak membuat RAM/Browser Colab crash.
total_points = y_true.size
sample_size = min(20000, total_points) # Ambil 20rb atau batas maksimal jika kurang
idx = np.random.choice(total_points, sample_size, replace=False)

y_true_sample = y_true.flatten()[idx]
y_pred_sample = y_pred.flatten()[idx]

# ==========================================
# VISUALISASI 1: SCATTER PLOT (PREDIKSI VS AKTUAL)
# ==========================================
plt.figure(figsize=(8, 8))
sns.scatterplot(x=y_true_sample, y=y_pred_sample, alpha=0.3, edgecolor=None, color='blue')

# Buat garis merah diagonal (Garis Kesempurnaan / Ideal Line y=x)
min_val = min(y_true_sample.min(), y_pred_sample.min())
max_val = max(y_true_sample.max(), y_pred_sample.max())
plt.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label="Perfect Prediction (y=x)")

plt.title("Scatter Plot: Prediction vs. Actual")
plt.xlabel("Original Protein Expression (Actual)")
plt.ylabel("AI Guess (Prediction)")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# ==========================================
# VISUALISASI 2: ANALISIS AHLI (HEATMAP)
# ==========================================
# Kita lihat 50 sel pertama dan 25 protein pertama untuk melihat kemiripan pola
num_cells = 50
num_proteins = 25

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Heatmap Aktual (Ground Truth)
sns.heatmap(y_true[:num_cells, :num_proteins], cmap="viridis", ax=axes[0], cbar=True)
axes[0].set_title("original pattern (Actual)")
axes[0].set_xlabel("ID Protein")
axes[0].set_ylabel("ID Sel")

# Heatmap Prediksi (Tebakan Model)
sns.heatmap(y_pred[:num_cells, :num_proteins], cmap="viridis", ax=axes[1], cbar=True)
axes[1].set_title("AI Guess Patterns (Predicsi)")
axes[1].set_xlabel("ID Protein")
axes[1].set_ylabel("ID Sel")

plt.suptitle("Heatmap Expression Protein: ACtual vs Prediction (50 Sel x 25 Protein)", fontsize=14, y=1.05)
plt.tight_layout()
plt.show()

# ==========================================
# VISUALISASI 3: DENSITY DISTRIBUTION (KDE PLOT)
# ==========================================
plt.figure(figsize=(10, 6))

# KDE Plot untuk melihat kelengkungan / distribusi dari nilai ekspresi
sns.kdeplot(y_true_sample, fill=True, color="green", alpha=0.5, label="Actual Data (Original)")
sns.kdeplot(y_pred_sample, fill=True, color="orange", alpha=0.5, label="AI guesses (Prediction)")

plt.title("Protein Expression Density Distribution (KDE Plot)")
plt.xlabel("Protein Expression Values")
plt.ylabel(" (Density)")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""

---

"""









